name: CI

on: 
  pull_request:
  push:

jobs:
  check-changed-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Get changed files
        id: get_changed_files
        uses: tj-actions/changed-files@v27
        with:
          files: 'src/**'

      - name: Display changed files
        run: echo "Changed files: ${{ steps.get_changed_files.outputs.changed_files }}"
